### ISSUE TITLE
I have some issue about CutQC , can someone help me out of my confusion? thanks

### ISSUE THREAD

**Issue by NicolasYL** [QuantumArchitecturePrinceton/QuantumArchitecturePrinceton.github.io#1]
![image](https://user-images.githubusercontent.com/47812418/103345660-f179b080-4acc-11eb-96f0-e25348d5578b.png)
![image](https://user-images.githubusercontent.com/47812418/103345677-fb031880-4acc-11eb-96c2-8e7c3f514278.png)
 in mine mind, cut one qubit wire into 8 sub-circuits,but I don't know exactly what it refers to?
In the first picture, what does the **"I-Z"** means?
Can you provide the corresponding code about CutQC?thanks a lot.

**Comment by weiT1993** [comment]
It produces 7 sub-circuit variations. Subcirc_1 measured in I,X,Y (3) + subcirc_2 initialized with 0,1,+,i (4).
Our code is publicly available here: https://zenodo.org/record/4329804#.YBgeMC1h0Tt.
